# Generated by Django 4.2.11 on 2024-04-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='chip',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='animal',
            name='info_animais',
            field=models.CharField(max_length=500, verbose_name='Sobre'),
        ),
        migrations.AlterField(
            model_name='historico_medico',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Receita'),
        ),
        migrations.AlterField(
            model_name='historico_medico',
            name='info_medica',
            field=models.CharField(max_length=50, verbose_name='Informacoes'),
        ),
        migrations.AlterField(
            model_name='historico_medico',
            name='voluntario_name',
            field=models.CharField(max_length=50, verbose_name='Voluntario'),
        ),
    ]
