# Generated by Django 4.2.11 on 2024-04-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animais', '0002_alter_animal_chip_alter_animal_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_medico',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receita/', verbose_name='Pdf Receita'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='chip',
            field=models.IntegerField(verbose_name='chip'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='historico_medico',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receita/', verbose_name='Foto Receita'),
        ),
    ]
