# Generated by Django 4.2.11 on 2024-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animais', '0004_animal_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='chip',
            field=models.CharField(max_length=15),
        ),
    ]
