# Generated by Django 5.0.4 on 2024-04-12 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animais', '0005_alter_animal_chip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-data'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'verbose_name': 'Raça', 'verbose_name_plural': 'Raças'},
        ),
        migrations.AddField(
            model_name='animal',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
