# -*- coding: utf-8 -*-
"""exercicio_modulo1_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whmTnP9oZU9M-1sToMS9biLvwWYciEnF
"""

salario = float(input("Digite aqui o seu salário"))

if salario <= 1903.98:
  desconto_IR = 0

elif salario >= 1903.99 and salario <= 2826.65:
  desconto_IR = salario * (7.5 / 100)

elif salario >= 2826.66 and salario <= 3751.05:
  desconto_IR = salario * (20 / 100)

elif salario >= 3751.06 and 4554.68:
  desconto_IR = salario * (22.5 / 100)

else:
  desconto_IR = salario * (27.5 / 100)

salario_liquido = salario - desconto_IR


print(
    f"\n Salário Bruto    R${salario:.2f}."
    f"\n(-) IR            R${desconto_IR:.2f}."
    f"\n Salário Líquido  R${salario_liquido:.2f}"
)