# Generated by Django 4.2.11 on 2024-04-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0011_alter_voluntario_options'),
        ('app_adotantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_voluntarios.voluntario'),
        ),
    ]
