# Generated by Django 4.2.11 on 2024-04-11 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_animais', '0005_alter_animal_chip'),
        ('app_adotantes', '0002_alter_adocao_voluntario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form_user',
            options={'ordering': ('-pk',), 'verbose_name': 'Pedido de adoção', 'verbose_name_plural': 'Pedidos de adoção'},
        ),
        migrations.AddField(
            model_name='form_user',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_animais.animal'),
        ),
        migrations.AddField(
            model_name='form_user',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em'),
        ),
        migrations.AddField(
            model_name='form_user',
            name='status',
            field=models.CharField(choices=[('p', 'Pendente'), ('a', 'Aprovado'), ('r', 'Recusado')], default='p', max_length=1),
        ),
        migrations.DeleteModel(
            name='Adocao',
        ),
    ]
