# Generated by Django 4.2.11 on 2024-04-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adotantes', '0004_alter_form_user_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form_user',
            options={'verbose_name': 'Pedido de adoção', 'verbose_name_plural': 'Pedidos de adoção'},
        ),
    ]
