# Generated by Django 5.0.4 on 2024-04-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adotantes', '0006_rename_email_form_user_email_adotante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_user',
            old_name='email_adotante',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='form_user',
            old_name='info_geral_adotante',
            new_name='informações',
        ),
        migrations.RenameField(
            model_name='form_user',
            old_name='nome_adotante',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='form_user',
            old_name='quant_animais',
            new_name='quantidade_de_animais',
        ),
        migrations.RenameField(
            model_name='form_user',
            old_name='telefone_adotante',
            new_name='telefone',
        ),
    ]
