# Generated by Django 4.2.11 on 2024-04-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefone', models.IntegerField(verbose_name=11)),
                ('profissão', models.CharField(max_length=500)),
                ('info_geral', models.CharField(max_length=500)),
            ],
        ),
    ]
