# Generated by Django 4.2.11 on 2024-04-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0003_alter_voluntario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='status',
            field=models.CharField(choices=[('p', 'Pendente'), ('a', 'Aprovado'), ('r', 'Recusado'), ('s', 'Saiu')], default='p', max_length=1),
        ),
    ]
