# Generated by Django 4.2.11 on 2024-04-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0004_voluntario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='info_geral',
            field=models.CharField(max_length=500, verbose_name='Informação'),
        ),
    ]
