# Generated by Django 4.2.11 on 2024-04-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0006_remove_voluntario_status_voluntario_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
    ]
