# Generated by Django 4.2.11 on 2024-04-07 04:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0007_alter_voluntario_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoinscricao',
            options={'verbose_name': 'pedido de inscrição', 'verbose_name_plural': 'pedidos de inscrição'},
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefone'),
        ),
    ]
