# Generated by Django 4.2.11 on 2024-04-07 08:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0008_alter_pedidoinscricao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
