# Generated by Django 4.2.11 on 2024-04-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0009_alter_voluntario_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'verbose_name': 'pedido de inscrição', 'verbose_name_plural': 'pedidos de inscrição'},
        ),
        migrations.AddField(
            model_name='voluntario',
            name='status',
            field=models.CharField(choices=[('p', 'Pendente'), ('a', 'Aprovado'), ('r', 'Recusado')], default='p', max_length=1),
        ),
        migrations.DeleteModel(
            name='PedidoInscricao',
        ),
    ]
