# Generated by Django 5.0.4 on 2024-04-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0010_alter_voluntario_options_voluntario_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'verbose_name': 'Inscrição voluntario', 'verbose_name_plural': 'Inscrição voluntarios'},
        ),
    ]
