# Generated by Django 5.0.4 on 2024-04-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntarios', '0011_alter_voluntario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'verbose_name': 'Inscrição de voluntario', 'verbose_name_plural': 'Inscrição de voluntarios'},
        ),
    ]
